[[- if .Values.provider  ]]
[[- if  eq .Values.provider.kind "capa"  ]]
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-k8s-initiator-app-deployment-capa
spec:
  background: true
  failurePolicy: Fail
  rules:
    - match:
        any:
          - resources:
              kinds:
                - App
      name: block-k8s-initiator-app-deployment-capa
      validate:
        message: K8s initiator app is not supported on CAPA.
        deny:
          conditions:
          - key: "{{request.object.spec.name}}"
            operator: Equals
            value: "k8s-initiator-app"
  validationFailureAction: Enforce
---
# https://github.com/giantswarm/giantswarm/issues/33418

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application.giantswarm.io/team: honeybadger
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
    rbac.kyverno.io/aggregate-to-reports-controller: "true"
  name: kyverno:gs-dx:block-k8s-initiator-app-deployment-capa
rules:
- apiGroups:
  - application.giantswarm.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
[[- end ]]
[[- end ]]
