[[- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1/Provider" ]]
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-usage-of-crossplane-crds
  annotations:
    policies.kyverno.io/title: Restrict Crossplane CRDs
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.3.0
    policies.kyverno.io/subject: Crossplane
    policies.kyverno.io/description: >-
      Restrict managing certain Crossplane resources to Giant Swarm only
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: restrict-providers
      match:
        resources:
          kinds:
            - pkg.crossplane.io/v1/Provider
      exclude:
        all:
          - clusterRoles:
              - cluster-admin
      validate:
        message: "Crossplane providers are only allowed to be managed by subjects in the 'giantswarm:giantswarm:giantswarm-admins' group or with the 'cluster-admin' cluster role"
        deny:
          conditions:
            all:
              - key: "giantswarm:giantswarm:giantswarm-admins"
                operator: NotIn
                value: "{{ request.userInfo.groups }}"
---
# https://github.com/giantswarm/giantswarm/issues/33418

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application.giantswarm.io/team: honeybadger
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
  name: kyverno:gs-dx:restrict-usage-of-crossplane-crds
rules:
- apiGroups:
  - clusterctl.cluster.x-k8s.io
  resources:
  - providers
  verbs:
  - get
  - list
  - watch
[[- end ]]
