apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-usage-of-crossplane-crds
  annotations:
    policies.kyverno.io/title: Restrict Crossplane CRDs
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.3.0
    policies.kyverno.io/subject: Crossplane
    policies.kyverno.io/description: >-
      TODO
spec:
  validationFailureAction: audit
  background: false
  rules:
    - name: restrict-providers
      match:
        resources:
          kinds:
            - pkg.crossplane.io/v1/Provider
#        subjects:
#          - kind: ServiceAccount
#            name: kustomize-controller
#            namespace: flux-giantswarm
      validate:
        message: "Crossplane providers are only allowed to be created by flux-giantswarm/kustomize-controller"
        deny:
          conditions:
            all:
              - key: "{{ serviceAccountName }}"
                operator: NotEquals
                value: kustomize-controller
              - key: "{{ serviceAccountNamespace }}"
                operator: NotEquals
                value: flux-giantswarm
