
version: 2.1

orbs:
  architect: giantswarm/architect@4.26.0

# commands:
#   run-ats:
#     parameters:
#       ats_version:
#         type: string
#         default: 0.1.4
#       chart_archive_prefix:
#         type: string
#       tests_dir:
#         type: string
#     steps:
#       - architect/run-tests-with-ats:
#           chart_archive_prefix: "<< parameters.chart_archive_prefix >>"
#           app-test-suite_version: "v<< parameters.ats_version >>"
#           app-test-suite_container_tag: "<< parameters.ats_version >>"
#           additional_app-test-suite_flags: "--external-cluster-version $KUBERNETES_VERSION --app-tests-pytest-tests-dir << parameters.tests_dir >>"

jobs:
  kyverno-tests:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      KYVERNO_VERSION: v1.8.0
    steps:
      - checkout
      - run:
          name: Download Kyverno CLI
          command: |
            curl -sLO https://github.com/kyverno/kyverno/releases/download/${KYVERNO_VERSION}/kyverno-cli_${KYVERNO_VERSION}_linux_x86_64.tar.gz
            tar -xf kyverno-cli_${KYVERNO_VERSION}_linux_x86_64.tar.gz
            ./kyverno version          
      - run:
          name: Run tests
          command: ./kyverno test "helm/kyverno-policies-dx/tests"

workflows:
  workflow:
    jobs:
      - kyverno-tests:
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute-chart-tests
          app-test-suite_container_tag: "0.2.3"
          filters:
            # Do not trigger the job on merge to main.
            branches:
              ignore:
                - main
          requires:
            - "push-kyverno-policies-dx-to-catalog"

      - architect/push-to-app-catalog:
          name: push-kyverno-policies-dx-to-catalog
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: "kyverno-policies-dx"
          context: "architect"
          # on_tag: false
          requires:
            - test-policies
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-kyverno-policies-dx-to-aws-app-collection
          context: architect
          app_name: "kyverno-policies-dx"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-kyverno-policies-dx-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: push-kyverno-policies-dx-to-capa-app-collection
          context: architect
          app_name: "kyverno-policies-dx"
          app_namespace: "giantswarm"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-kyverno-policies-dx-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
        # On Azure, the "Check deprecated APIs" policy is already deployed with policies-common as part of Azure releases.
        # When Azure/CAPZ no longer ships the old policy app, this push to the azure collection should be enabled.
      # - architect/push-to-app-collection:
      #     name: push-kyverno-policies-dx-to-azure-app-collection
      #     context: architect
      #     app_name: "kyverno-policies-dx"
      #     app_namespace: "giantswarm"
      #     app_collection_repo: "azure-app-collection"
      #     requires:
      #       - push-kyverno-policies-dx-to-catalog
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v.*/

      - architect/push-to-app-collection:
          name: push-kyverno-policies-dx-to-kvm-app-collection
          context: architect
          app_name: "kyverno-policies-dx"
          app_namespace: "giantswarm"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-kyverno-policies-dx-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-kyverno-policies-dx-to-openstack-app-collection
          context: architect
          app_name: "kyverno-policies-dx"
          app_namespace: "giantswarm"
          app_collection_repo: "openstack-app-collection"
          requires:
            - push-kyverno-policies-dx-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-kyverno-policies-dx-to-gcp-app-collection
          context: architect
          app_name: "kyverno-policies-dx"
          app_namespace: "giantswarm"
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-kyverno-policies-dx-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-kyverno-policies-dx-to-cloud-director-app-collection
          context: architect
          app_name: "kyverno-policies-dx"
          app_namespace: "giantswarm"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-kyverno-policies-dx-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
